###############################
## 4gekkman/docker-mysql-dev ##
###############################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Установить необходимые пакеты
##

# 1. Базовый образ и разработчики
FROM mysql:latest
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Установить необходимые пакеты
RUN apt-get update && apt-get install -y \

  supervisor \
  ; exit 0

