###############################
## 4gekkman/docker-mysql-dev ##
###############################
## Оглавление
##  
##  1. Базовый образ и разработчики
##

# 1. Базовый образ и разработчики
FROM mysql:latest
MAINTAINER German Manvelov <4gekkman@gmail.com>




